# ==============================================================================
# HTCondor提交脚本
# ==============================================================================
universe       = vanilla
should_transfer_files   = NO

# 基本配置
executable     = /storage/fdunphome/wangchunzheng/cve_ampt_light/beforeART/run.sh
arguments      = $(INPUT_FILE) $(Process)

# 日志配置
output         = /storage/fdunphome/wangchunzheng/cve_ampt_light/beforeART/outputs/job_$(Process).out
error          = /storage/fdunphome/wangchunzheng/cve_ampt_light/beforeART/outputs/job_$(Process).err
log            = /storage/fdunphome/wangchunzheng/cve_ampt_light/beforeART/outputs/job_$(Process).log

queue INPUT_FILE from /storage/fdunphome/wangchunzheng/cve_ampt_light/joblist_beforeART.txt
